version: '2'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    ports:
      - "8080:80"
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
    restart: always

  terraform:
    image:  hashicorp/terraform:1.0.0
    volumes:
      - ./terraform:/data/
    working_dir: /data

